# 分钟数据源路径
[SOURCE]
path = /Users/xgw/Desktop/stock_data

# 目标库表名
[TARGET]
# 目标库路径
path = /Users/xgw/workspace/Data/stock.duckdb

# QMT服务器配置
[QMT-SERVER]
base_url = http://localhost:8000
token = xxx

# 本地补全数据库数据配置
[COMPLETION]
# 是否需要重建（当补全范围可能与已有数据有重叠时，需要重建）
rebuild = false
# 本地数据开始日期
start_date = 20200101
# 本地数据结束日期
end_date = 20251127
# 远端1d数据开始日期
remote_1d_start_date = 20200101 
# 远端1m数据开始日期
remote_1m_start_date = 20251001 

